# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-18 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='/images/ava.png', upload_to='images/'),
        ),
    ]
